### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tanaka-shoya-2020** [tanaka-shoya-2020/furima-30448#9]
自身のフリマアプリのURL
 https://furima-30448.herokuapp.com/

Basic認証のIDとパスワード 
 ID: t.shoya,  password: 30448

出品者用のメールアドレスとパスワード 
メールアドレス: foobar1@gmail.com
パスワード:  foobar1

購入者用のメールアドレスとパスワード
メールアドレス: foobar@gmail.com
パスワード:   foobar1

購入用カードの番号・期限・セキュリティコード 
番号:4242424242424242
期限: 11月22年
セキュリティコード 123

**Comment by vesper1102609** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**

**Comment by tanaka-shoya-2020** [comment]
tomohumi1109 様

挙動確認をしていただきまして、ありがとうございます。
LGTMをいただきましたので、あとは追加実装などをチーム内で進めさせていただこうと思います。
